from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

import numpy as np

from .domain import CastObservation, CatchObservation, FishingObservation, RuntimeSnapshot


class VisionPort(Protocol):
    def observe_scene(
        self, expected_bar_length_pixels: int | None = None
    ) -> FishingObservation: ...
    def begin_cast(self) -> None: ...
    def observe_cast(self) -> CastObservation: ...
    def detect_bite(self) -> bool: ...
    def read_catch(self) -> CatchObservation: ...
    def latest_frame(self) -> np.ndarray | None: ...
    def latest_catch_card(self) -> np.ndarray | None: ...
    def close(self) -> None: ...


class InputPort(Protocol):
    def set_duty(self, duty_ratio: float) -> None: ...
    def press(self) -> None: ...
    def release(self) -> None: ...
    def tap(self, duration_seconds: float = 0.04) -> None: ...
    def idle(self) -> None: ...
    def close(self) -> None: ...


class DashboardPort(Protocol):
    def publish(self, snapshot: RuntimeSnapshot) -> None: ...
    def log(self, message: str, *, level: str = "info") -> None: ...
    def close(self) -> None: ...


class Clock(Protocol):
    def __call__(self) -> float: ...


Sleep = Callable[[float], None]
